from turtle import *
from random import randint
import turtle
pensize(5)

turtle.color("yellow")
bgcolor("black")
left(100)
forward(100)
left(50)
forward(50)
left(100)
forward(100)

left(100)
penup()
forward(30)
pendown()

left(100)
forward(100)
left(50)
forward(50)
left(100)
forward(100)

doors_with_ghost = randint(1, 2)
print("There are 2 doors. Behind one there is a ghost.")
print("Which door will you open?")
doors = input("")
doors = int(doors)
turtle.clear()
if doors == doors_with_ghost:
    print("You lost!")
    turtle.color("white")
    bgcolor("black")
    right(200)
    pendown()
    right(100)
    forward(50)
    left(100)
    forward(150)
    left(100)
    forward(50)
    penup()
    forward(42)
    pendown()
    forward(8)
    left(75)
    penup()
    forward(100)
    pendown()
    forward(8)
    penup()
    forward(42)

else:
    print("You won!")
    turtle.color("black")
    bgcolor("white")
    smiles = turtle.Turtle()    
    smiles.penup()
    smiles.goto(-75,150)
    smiles.pendown()
    smiles.circle(10)
    smiles.penup()
    smiles.goto(75,150)
    smiles.pendown()
    smiles.circle(10)
    smiles.penup()
    smiles.goto(0,0)
    smiles.pendown()
    smiles.circle(100,90)
    smiles.penup()
    smiles.setheading(180)
    smiles.goto(0,0)
    smiles.pendown()
    smiles.circle(-100,90)

input("Press ENTER to continue...")


